POST http://localhost:5000/users/register
Content-Type: application/json

{
    "name": "Pavan L",
    "email": "pavan.l8149@ltimindtree.com",
    "username": "pavan1",
    "password": "pavan" ,
    "role" : "user"

}
###
POST http://localhost:5000/users/login
Content-Type: application/json

{
    "username":"pavan1",
    "password": "pavan"
}
###
# POST http://local
